### ISSUE TITLE
can't find DentalSegmentator in extension manager of slicer

### ISSUE THREAD

**Issue by DanpengDing** [gaudot/SlicerDentalSegmentator#11]

**Comment by DanpengDing** [comment]
3d slicer 5.6.1 windows

**Comment by Thibault-Pelletier** [comment]
@DanpengDing thanks for your reply.
The dental segmentator is only available in the package manager starting from version 5.7 onwards on every OS.

If you'd like to test it, you can either : 
- Download the preview 5.7 version on https://download.slicer.org/
- Manually install the extension in previous versions of 3D Slicer by downloading both this extension and the SlicerNNUNet extension
