### ISSUE TITLE
Request for dataset used to train nnUNet

### ISSUE THREAD

**Issue by sniper0110** [gaudot/SlicerDentalSegmentator#16]
Hi,

First of all, thank you very much for providing this tool. It's truly amazing!

I was wondering if it's possible for you to release also the dataset that was used to train your nnUNet model. This way anyone can retrain the model with different nnUNet configs if necessary.

Thanks.

**Comment by GauthierDot** [comment]
Dear @sniper0110 

Thank you for your message and your interest. We would be glad to share the dataset, but unfortunately it is impossible due to our hospitals data regulations. 

Best regards
Gauthier
