### ISSUE TITLE
Why is there no edit ui button

### ISSUE THREAD

**Issue by DanpengDing** [gaudot/SlicerDentalSegmentator#17]
Hello, I want to develop a tumor segmentation plugin based on this plugin, but this plugin does not have the Edit ui button 。

**Comment by Thibault-Pelletier** [comment]
Hi @DanpengDing,

This project doesn't use Qt .ui file.
The UI is directly implemented in python in the following file : https://github.com/gaudot/SlicerDentalSegmentator/blob/main/DentalSegmentator/DentalSegmentatorLib/SegmentationWidget.py#L28
