### ISSUE TITLE
Asking for nnUNet usage.

### ISSUE THREAD

**Issue by deepsea920415** [gaudot/SlicerDentalSegmentator#3]
I've tested your pretrained model.
It was amazing.

And I have a question.
If I have dataset for dental CBCT images with every-tooth labeling, is it possible to train individual tooth segmentation neural network with nnUNet?

I want to know your expertise opinion.

Thank you.

**Comment by Thibault-Pelletier** [comment]
Hi @deepsea920415,

Thank you for testing our extension and pretrained weights.
Yes, if you have labeled data with every-tooth labeling, it will also work with the nnUNet library.

The most well known nnUNet success is the TotalSegmentator model which has 117 distinct classes.
I recommend you have a look at the nnUNet documentation to get started : https://github.com/MIC-DKFZ/nnUNet?tab=readme-ov-file#how-to-get-started

Best,
Thibault

**Comment by deepsea920415** [comment]
Thanks.
