### ISSUE TITLE
Request for Python Standalone Code of DentalSegmentator

### ISSUE THREAD

**Issue by bstartek** [gaudot/SlicerDentalSegmentator#4]
Hello everyone,

I am currently exploring the possibilities of integrating the Slicer DentalSegmentator into my workflow using Blender. I have downloaded the model and am considering adapting it with VTK, ITK to achieve prediction results in pure Python.

To this end, I am interested in a non-Slicer3d-optimized version of the DentalSegmentator project written in Python, which does not require integration into Slicer. My goal is to generate STL models through Blender's internal Python compilation and then import them into a Blender scene for further manipulation.

Could the authors or anyone in the community please share a link to the code or the code itself if available? This would greatly help in streamlining the process and experimenting directly within Blender.

Thank you very much for your assistance!
Bartosz Startek

**Comment by Thibault-Pelletier** [comment]
Hi @bstartek ,

Thank you for your interest in our extension.
As described in the README, this extension is based on the nnUNet library.

In this extension, we call the nnUNet library with the DentalSegmentator weights and the patient's image converted to NIFTI.
This is then loaded back to 3D Slicer for some cleanup and conversion to close surface from 3D Segmentation data.

If you want to have a look at the nnUNet call logic, you can have a look at the SlicerNNUNet extension available here : https://github.com/KitwareMedical/SlicerNNUnet/blob/main/SlicerNNUnet/SlicerNNUNetLib/SegmentationLogic.py

You can also have a look at the nnUNet library here : https://github.com/MIC-DKFZ/nnUNet

Best,
Thibault

**Comment by bstartek** [comment]
Hi @Thibault-Pelletier,

Thank you for your detailed response and the resources provided. I appreciate your guidance on how to explore the nnUNet call logic within the SlicerNNUNet extension.

I have a specific question regarding the training of the model used in this extension: Could you clarify whether the model was trained using version 1 or version 2 of the nnUNet library? Understanding this will help ensure compatibility with my current setup.

Looking forward to your reply.

Best regards,
Bartosz Startek

**Comment by GauthierDot** [comment]
Dear Bartosz

Thank you for your interest in our work. We used nnUNet library v2.2.1 for the training of the model. 

For additional information about the training and inference process, you could refer to [our paper](https://www.medrxiv.org/content/10.1101/2024.03.18.24304458v1) and [Zenodo record of our model](https://zenodo.org/records/10829675).  

Please let us know how it goes with Blender :) !

Best,
Gauthier

**Comment by bstartek** [comment]
Hey everyone! I've just written some code for Blender that I thought might be useful to others, especially if you're working with medical imaging and Blender. You can run it directly from Python, and I've set up a control in Blender that automates a few key steps:

1. Converts DCM files to NIfTI format.
2. Performs image interference.
3. Saves the result back to NIfTI.
4. Converts NIfTI files to STL models.
5. Imports the STL models into Blender.

[nnUNet_DentalSegmentator.zip](https://github.com/gaudot/SlicerDentalSegmentator/files/15180969/nnUNet_DentalSegmentator.zip)


I also integrated nnU-NetV2, which is an incredibly fast and easy-to-configure neural network. I'm officially a fan as of today! 😄

Feel free to use it and let me know how it works for you!

**Comment by GauthierDot** [comment]
Dear Bartosz

Thank you for sharing your code ! 

Best,
Gauthier

**Comment by damjo** [comment]
> Hey everyone! I've just written some code for Blender that I thought might be useful to others, especially if you're working with medical imaging and Blender. You can run it directly from Python, and I've set up a control in Blender that automates a few key steps:
> 
> 1. Converts DCM files to NIfTI format.
> 2. Performs image interference.
> 3. Saves the result back to NIfTI.
> 4. Converts NIfTI files to STL models.
> 5. Imports the STL models into Blender.
> 
> [nnUNet_DentalSegmentator.zip](https://github.com/gaudot/SlicerDentalSegmentator/files/15180969/nnUNet_DentalSegmentator.zip)
> 
> I also integrated nnU-NetV2, which is an incredibly fast and easy-to-configure neural network. I'm officially a fan as of today! 😄
> 
> Feel free to use it and let me know how it works for you!

what are the pre requisities in blender? can i run it direcly with dicom files?

**Comment by bstartek** [comment]
> > Hey everyone! I've just written some code for Blender that I thought might be useful to others, especially if you're working with medical imaging and Blender. You can run it directly from Python, and I've set up a control in Blender that automates a few key steps:
> > 
> > 1. Converts DCM files to NIfTI format.
> > 2. Performs image interference.
> > 3. Saves the result back to NIfTI.
> > 4. Converts NIfTI files to STL models.
> > 5. Imports the STL models into Blender.
> > 
> > [nnUNet_DentalSegmentator.zip](https://github.com/gaudot/SlicerDentalSegmentator/files/15180969/nnUNet_DentalSegmentator.zip)
> > I also integrated nnU-NetV2, which is an incredibly fast and easy-to-configure neural network. I'm officially a fan as of today! 😄
> > Feel free to use it and let me know how it works for you!
> 
> what are the pre requisities in blender? can i run it direcly with dicom files?

You will need:
                "SimpleITK": "SimpleITK"
                "torch": "torch==2.2.2 torchvision==0.17.2 torchaudio==2.2.2 --extra-index-url https://download.pytorch.org/whl/cu118",
                "nnunetv2": "nnunetv2",
                "stl": "numpy-stl",

You can load dict with *.dcm files from Blender

**Comment by damjo** [comment]
how did you load your dcm?

**Comment by bstartek** [comment]
> how did you load your dcm?

![Zrzut ekranu 2024-05-02 225548](https://github.com/gaudot/SlicerDentalSegmentator/assets/74208129/1c3cfaac-68ad-41ab-a860-32ca756a7633)

I done it via "import bpy" and interna blender GUI

**Comment by damjo** [comment]
thank you for helping me, but i m a beginner with python
my blender version is 3.6 and ortogon is on 2.9
i dont hqve such menu

**Comment by pzaffino** [comment]
Hi,
thanks for your code.

I am interested in segmenting a CBCT directly from the python environment.
I saw your code and I was not able to get a segmentation (I got an error about tensor dimension mismatch in the model).

Here is a snippet of code (instead of the CBCT, just for this snippet, I put a random tensor with the same shape as my image).
You need to change only the path with the pretrained model.

```
import torch
import torch.nn as nn
import numpy as np

from nnunetv2.paths import nnUNet_results, nnUNet_raw
from batchgenerators.utilities.file_and_folder_operations import join, load_json
from nnunetv2.inference.predict_from_raw_data import nnUNetPredictor

class pretrainednnUnet(nn.Module):
    def __init__(self, device, root_path) -> None:
        super(pretrainednnUnet, self).__init__()
        
        predictor = nnUNetPredictor(
            tile_step_size=0.5,
            use_gaussian=True,
            use_mirroring=True,
            perform_everything_on_device=True,
            device=device,
            verbose=False,
            verbose_preprocessing=False,
            allow_tqdm=True)

        predictor.initialize_from_trained_model_folder(
            root_path,
            use_folds=(0,),  # Use the first fold
            checkpoint_name='checkpoint_final.pth')

        self.model=predictor.network

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = self.model(x)
        return x

device = torch.device("cuda")
root_path = 'PATH/Dataset112_DentalSegmentator_v100/nnUNetTrainer__nnUNetPlans__3d_fullres/'
model = pretrainednnUnet(device = device, root_path = root_path).to(device)

cbct = torch.randn((1,1,401,374,220)).float().to(device)
segmentations = model(cbct)
```

Thanks a lot.
Paolo

**Comment by Thibault-Pelletier** [comment]
Hi @pzaffino,

If you want to use the nnUNet library directly with the pretrained weights, it would be easier to directly call the full nnUNet prediction script.

The prediction script does a preprocessing > inference > post processing.

The preprocessing consists in reshaping the input data for consistent input for the nnUNet sliding window inference which is why you have the error.

You can have a look at nnUNet examples here : https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunetv2/inference/examples.py

**Comment by KochabStar** [comment]
> 大家好！我刚刚为 Blender 编写了一些代码，我认为这些代码可能对其他人有用，特别是如果您正在使用医学成像和 Blender。您可以直接从 Python 运行它，并且我在 Blender 中设置了一个控件，可以自动执行几个关键步骤：
> 
> 1. 将 DCM 文件转换为 NIfTI 格式。
> 2. 执行图像干涉。
> 3. 将结果保存回 NIfTI。
> 4. 将 NIfTI 文件转换为 STL 模型。
> 5. 将 STL 模型导入 Blender 中。
> 
> [nnUNet_DentalSegmentator.zip](https://github.com/gaudot/SlicerDentalSegmentator/files/15180969/nnUNet_DentalSegmentator.zip)
> 
> 我还集成了 nnU-NetV2，这是一个非常快速且易于配置的神经网络。从今天开始，我正式成为粉丝了！😄
> 
> 随意使用它，让我知道它如何为您工作！



> Hey everyone! I've just written some code for Blender that I thought might be useful to others, especially if you're working with medical imaging and Blender. You can run it directly from Python, and I've set up a control in Blender that automates a few key steps:
> 
> 1. Converts DCM files to NIfTI format.
> 2. Performs image interference.
> 3. Saves the result back to NIfTI.
> 4. Converts NIfTI files to STL models.
> 5. Imports the STL models into Blender.
> 
> [nnUNet_DentalSegmentator.zip](https://github.com/gaudot/SlicerDentalSegmentator/files/15180969/nnUNet_DentalSegmentator.zip)
> 
> I also integrated nnU-NetV2, which is an incredibly fast and easy-to-configure neural network. I'm officially a fan as of today! 😄
> 
> Feel free to use it and let me know how it works for you!

Please how did you smooth the stl surface, my stl import is as follows
![171251](https://github.com/user-attachments/assets/73023086-102d-466e-bbb7-feedfb00041e)

**Comment by damjo** [comment]
> > 大家好！我刚刚为 Blender 编写了一些代码，我认为这些代码可能对其他人有用，特别是如果您正在使用医学成像和 Blender。您可以直接从 Python 运行它，并且我在 Blender 中设置了一个控件，可以自动执行几个关键步骤：
> > 
> > 1. 将 DCM 文件转换为 NIfTI 格式。
> > 2. 执行图像干涉。
> > 3. 将结果保存回 NIfTI。
> > 4. 将 NIfTI 文件转换为 STL 模型。
> > 5. 将 STL 模型导入 Blender 中。
> > 
> > [nnUNet_DentalSegmentator.zip](https://github.com/gaudot/SlicerDentalSegmentator/files/15180969/nnUNet_DentalSegmentator.zip)
> > 我还集成了 nnU-NetV2，这是一个非常快速且易于配置的神经网络。从今天开始，我正式成为粉丝了！😄
> > 随意使用它，让我知道它如何为您工作！
> 
> > Hey everyone! I've just written some code for Blender that I thought might be useful to others, especially if you're working with medical imaging and Blender. You can run it directly from Python, and I've set up a control in Blender that automates a few key steps:
> > 
> > 1. Converts DCM files to NIfTI format.
> > 2. Performs image interference.
> > 3. Saves the result back to NIfTI.
> > 4. Converts NIfTI files to STL models.
> > 5. Imports the STL models into Blender.
> > 
> > [nnUNet_DentalSegmentator.zip](https://github.com/gaudot/SlicerDentalSegmentator/files/15180969/nnUNet_DentalSegmentator.zip)
> > I also integrated nnU-NetV2, which is an incredibly fast and easy-to-configure neural network. I'm officially a fan as of today! 😄
> > Feel free to use it and let me know how it works for you!
> 
> Please how did you smooth the stl surface, my stl import is as follows ![171251](https://private-user-images.githubusercontent.com/129256286/400705962-73023086-102d-466e-bbb7-feedfb00041e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYyODUwOTUsIm5iZiI6MTczNjI4NDc5NSwicGF0aCI6Ii8xMjkyNTYyODYvNDAwNzA1OTYyLTczMDIzMDg2LTEwMmQtNDY2ZS1iYmI3LWZlZWRmYjAwMDQxZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwN1QyMTE5NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MTNmZTMwYzI0YjQyMjYyZmNmMzMzNDZiNDU0OTg2Mjc1NDUzZDk2ZWRlYWM1Y2EyYTQ3ZTZkZTU0YTYzODU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2APJFMpeAcguxx-jldGnsASlNyINIoqkCE3CcI1kfxw)

where do i copy this script before running it?

**Comment by KochabStar** [comment]
> > > 大家好！我刚刚为 Blender 编写了一些代码，我认为这些代码可能对其他人有用，特别是如果您正在使用医学成像和 Blender。您可以直接从 Python 运行它，并且我在 Blender 中设置了一个控件，可以自动执行几个关键步骤：
> > > 
> > > 1. 将 DCM 文件转换为 NIfTI 格式。
> > > 2. 执行图像干涉。
> > > 3. 将结果保存回 NIfTI。
> > > 4. 将 NIfTI 文件转换为 STL 模型。
> > > 5. 将 STL 模型导入 Blender 中。
> > > 
> > > [nnUNet_DentalSegmentator.zip](https://github.com/gaudot/SlicerDentalSegmentator/files/15180969/nnUNet_DentalSegmentator.zip)
> > > 我还集成了 nnU-NetV2，这是一个非常快速且易于配置的神经网络。从今天开始，我正式成为粉丝了！😄
> > > 随意使用它，让我知道它如何为您工作！
> > 
> > 
> > > Hey everyone! I've just written some code for Blender that I thought might be useful to others, especially if you're working with medical imaging and Blender. You can run it directly from Python, and I've set up a control in Blender that automates a few key steps:
> > > 
> > > 1. Converts DCM files to NIfTI format.
> > > 2. Performs image interference.
> > > 3. Saves the result back to NIfTI.
> > > 4. Converts NIfTI files to STL models.
> > > 5. Imports the STL models into Blender.
> > > 
> > > [nnUNet_DentalSegmentator.zip](https://github.com/gaudot/SlicerDentalSegmentator/files/15180969/nnUNet_DentalSegmentator.zip)
> > > I also integrated nnU-NetV2, which is an incredibly fast and easy-to-configure neural network. I'm officially a fan as of today! 😄
> > > Feel free to use it and let me know how it works for you!
> > 
> > 
> > Please how did you smooth the stl surface, my stl import is as follows ![171251](https://private-user-images.githubusercontent.com/129256286/400705962-73023086-102d-466e-bbb7-feedfb00041e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYyODUwOTUsIm5iZiI6MTczNjI4NDc5NSwicGF0aCI6Ii8xMjkyNTYyODYvNDAwNzA1OTYyLTczMDIzMDg2LTEwMmQtNDY2ZS1iYmI3LWZlZWRmYjAwMDQxZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwN1QyMTE5NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MTNmZTMwYzI0YjQyMjYyZmNmMzMzNDZiNDU0OTg2Mjc1NDUzZDk2ZWRlYWM1Y2EyYTQ3ZTZkZTU0YTYzODU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2APJFMpeAcguxx-jldGnsASlNyINIoqkCE3CcI1kfxw)
> 
> where do i copy this script before running it?

I modified it based on the code in the package nnUNet_DentalSegmentator.zip

**Comment by damjo** [comment]
> > > > 大家好！我刚刚为 Blender 编写了一些代码，我认为这些代码可能对其他人有用，特别是如果您正在使用医学成像和 Blender。您可以直接从 Python 运行它，并且我在 Blender 中设置了一个控件，可以自动执行几个关键步骤：
> > > > 
> > > > 1. 将 DCM 文件转换为 NIfTI 格式。
> > > > 2. 执行图像干涉。
> > > > 3. 将结果保存回 NIfTI。
> > > > 4. 将 NIfTI 文件转换为 STL 模型。
> > > > 5. 将 STL 模型导入 Blender 中。
> > > > 
> > > > [nnUNet_DentalSegmentator.zip](https://github.com/gaudot/SlicerDentalSegmentator/files/15180969/nnUNet_DentalSegmentator.zip)
> > > > 我还集成了 nnU-NetV2，这是一个非常快速且易于配置的神经网络。从今天开始，我正式成为粉丝了！😄
> > > > 随意使用它，让我知道它如何为您工作！
> > > 
> > > 
> > > > Hey everyone! I've just written some code for Blender that I thought might be useful to others, especially if you're working with medical imaging and Blender. You can run it directly from Python, and I've set up a control in Blender that automates a few key steps:
> > > > 
> > > > 1. Converts DCM files to NIfTI format.
> > > > 2. Performs image interference.
> > > > 3. Saves the result back to NIfTI.
> > > > 4. Converts NIfTI files to STL models.
> > > > 5. Imports the STL models into Blender.
> > > > 
> > > > [nnUNet_DentalSegmentator.zip](https://github.com/gaudot/SlicerDentalSegmentator/files/15180969/nnUNet_DentalSegmentator.zip)
> > > > I also integrated nnU-NetV2, which is an incredibly fast and easy-to-configure neural network. I'm officially a fan as of today! 😄
> > > > Feel free to use it and let me know how it works for you!
> > > 
> > > 
> > > Please how did you smooth the stl surface, my stl import is as follows ![171251](https://private-user-images.githubusercontent.com/129256286/400705962-73023086-102d-466e-bbb7-feedfb00041e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYyODUwOTUsIm5iZiI6MTczNjI4NDc5NSwicGF0aCI6Ii8xMjkyNTYyODYvNDAwNzA1OTYyLTczMDIzMDg2LTEwMmQtNDY2ZS1iYmI3LWZlZWRmYjAwMDQxZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwN1QyMTE5NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MTNmZTMwYzI0YjQyMjYyZmNmMzMzNDZiNDU0OTg2Mjc1NDUzZDk2ZWRlYWM1Y2EyYTQ3ZTZkZTU0YTYzODU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2APJFMpeAcguxx-jldGnsASlNyINIoqkCE3CcI1kfxw)
> > 
> > 
> > where do i copy this script before running it?
> 
> I modified it based on the code in the package nnUNet_DentalSegmentator.zip

I am a beginner in Python, and I don't really understand how to configure my Blender so that it works. Could you make me a small tutorial on how to configure the Blender and Python folders? Thank you in advance for everything and for the time I am taking from you, but it would greatly help me to get this module working directly in Blender.
