### ISSUE TITLE
API service decision request

### ISSUE THREAD

**Issue by DimIsaev** [gaudot/SlicerDentalSegmentator#5]
Hello

  thanks for your wonderful extension

how to implement an inference model into a separate API service based on FAST_API or a similar one, so that you can deploy the model on an instance with a powerful GPU and give access to several low-power workstations with a slicer using the API

Thank you

**Comment by Thibault-Pelletier** [comment]
Hi @DimIsaev ,

To create an API for deployment, you can use one of the following methods : 

- Create a server running directly the nnUNet library 
- Create a script and call 3D Slicer in command line to run the DentalSegmentator segmentation and export the results
- Use 3D Slicer to run the server directly

If you want to use the segmentation without any GUI, options 1 or 2 would be the easiest.
Option 2 would allow you to have some cleanup for the segmentation and more export options but will be harder to debug.

Best,
Thibault
