### ISSUE TITLE
The error between nnUNet and SlicerDentalSegmentator

### ISSUE THREAD

**Issue by PrideDream** [gaudot/SlicerDentalSegmentator#6]
I came across a mistake :
```
RuntimeError: Invalid nnUNet configuration. Model folder is missing the following folds : [0].
Your model weight folder path should look like the following :
Dataset<dataset_id>/<trainer_name>__<plan_name>__<conf_name>

It should also contain a dataset.json file and fold_<i_fold> folders with model weights.

Provided model dir :
D:\ProgramData\slicer.org\Slicer 5.7.0-2024-05-15\slicer.org\Extensions-32859\DentalSegmentator\lib\Slicer-5.7\qt-scripted-modules\Resources\ML
```
It seems the path "DentalSegmentator\Resources\ML" created in SlicerDentalSegmentator is not well recognized by the nnUNet  library.

**Comment by Thibault-Pelletier** [comment]
Hi @PrideDream,

Thank you for your feedback and your interest in our extension.
It seems the model may not have been correctly downloaded / extracted in your ML folder.

To make up for that, you can follow the troubleshooting here : [GitHub - gaudot/SlicerDentalSegmentator: 3D Slicer extension for fully-automatic segmentation of CT and CBCT dental volumes.](https://github.com/gaudot/SlicerDentalSegmentator?tab=readme-ov-file#failed-to-download--find-weights)

It consists in :

Downloading the latest .zip file from the release and extracting it in the DentalSegmentator\Resources\ML folder
Creating a download_info.json in the ML folder with the following content : { "download_url": "https://github.com/gaudot/SlicerDentalSegmentator/releases/download/v1.0.0-alpha/Dataset111_453CT_v100.zip" }
Please let me know if that solves the issue on your end.

Best,
Thibault

**Comment by PrideDream** [comment]
Thank you very much!!! 
The error is caused by file path. 
By the way. Providing a tree diagram or screenshot of the file path will be more newbie friendly.
