### ISSUE TITLE
Use our own nnUNet model weights

### ISSUE THREAD

**Issue by amine0110** [gaudot/SlicerDentalSegmentator#9]
Hello,

First of all, thank you very much for this amazing work!

I have just one question that can help me for a project! If I have my own model weight and I want to create an extension that does the same thing that your extension, how can I use the code?

Do I just need to import the python code or how it works?

If you have a documentation that explains the steps to follow this will help a lot :)

Best regards

**Comment by Thibault-Pelletier** [comment]
Hi @amine0110,

Thank you for using our extension.
If you are creating an nnUNet based extension, you may be interested in using directly the [SlicerNNUNet extension](https://github.com/KitwareMedical/SlicerNNUnet). 

The SlicerNNUNet extension provides the building blocks to create new NNUNet extensions.

The SlicerDentalSegmentator uses it for the segmentation logic and adds the following features : 

- Segment editor integration
- Additional segmentation post processing curated for dental model
- Segments color / opacity setting
- Integrated STL and other formats exports

You can find calls to the SlicerNNUNet extension in the SlicerDentalSegmentator here : 

- Install :https://github.com/gaudot/SlicerDentalSegmentator/blob/main/DentalSegmentator/DentalSegmentatorLib/SegmentationWidget.py#L550
- Logic instantiation : https://github.com/gaudot/SlicerDentalSegmentator/blob/main/DentalSegmentator/DentalSegmentatorLib/SegmentationWidget.py#L563
- Logic signal connection : https://github.com/gaudot/SlicerDentalSegmentator/blob/main/DentalSegmentator/DentalSegmentatorLib/SegmentationWidget.py#L570
- Run segmentation : https://github.com/gaudot/SlicerDentalSegmentator/blob/main/DentalSegmentator/DentalSegmentatorLib/SegmentationWidget.py#L244

Best,
Thibault

**Comment by amine0110** [comment]
Hi @Thibault-Pelletier 

Thank you for your reply!

I think, I have seen the repo about slicer nnunet before, but my concerne is that how to install the extension in slicer (when the code is in my local).

Do I just need to upload the code or how it will be?

Also I had another question in mind, in the SlicerDentalSegmentator, you are using an Apache license and in the SlicerNNUnet repo they are putting BSD license!

Is there something that changed! Is it about the data?

Thanks again for your reply and the good work

Regards
